### ISSUE TITLE
xbmc.python 3.0.0 ABI compatability

### ISSUE THREAD

**Issue by MilhouseVH** [b-jesch/script.program.driverselect#3]
Now that https://github.com/xbmc/xbmc/pull/17188 has merged, Kodi 19 provides only `xbmc.python 3.0.0`, which means this add-on is currently incompatible with Kodi 19.

The [recommendation](https://forum.kodi.tv/showthread.php?tid=351745&pid=2924607#pid2924607) is to create two branches, one for Kodi 18/Leia (`xbmc.python 2.25.0`) and another for Kodi 19/Matrix (`xbmc.python 3.0.0`).

**Comment by b-jesch** [comment]
Issue is solving by creating a branch 'Matrix' and bumped the needed versions to 3.0.0. (python) and 11.2.0 (json). Note that I also bumped the version of the addon to 3.0.0 - that should indicate the affiliation with Matrix.
